### ISSUE TITLE
Inlining failed for std::deque

### ISSUE THREAD

**Issue by Morwenn** [tvanslyke/timsort-cpp#2]
I was running a few benchmarks again to make sure that your implementation was still faster than the gfx one even for `std::deque` (spoiler: it provides huge improvements for most patterns, and is just slightly slower for mostly sorted data, but not enough matter), and ran in this warning wtih GCC 7 -O3:

> warning: inlining failed in call to 'void tim::internal::_timsort(It, It, Comp) [with It = std::_Deque_iterator<fake_int, fake_int&, fake_int*>; Comp = std::less<void>]': --param large-stack-frame-growth limit reached [-Winline]

Considering that the function `_timsort` is already a template, you can probably get rid of `inline` which serves no ODR purpose here, and let the compiler infer what can be inlined.

EDIT: also side question while I'm at it: you don't have header guards for utils.h, is it ok?

**Comment by tvanslyke** [comment]
Sorry taking so long to respond, my github notifications have apparently been going to an old email address.  I've pushed a fix for the header guard on utils.h and removed a number of extraneous `inline`s in timsort.h.  I wasn't able to produce the warning from gcc, even with -Winline, but it should be all fixed now if that warning was the only one you came across.

**Comment by Morwenn** [comment]
I don't have the warning anymore. Thanks for fixing the issue :)
